# Generated by Django 6.0.4 on 2026-04-22 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_boqitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='boqitem',
            name='unit',
            field=models.CharField(choices=[('M', 'Meter (M)'),('M2', 'Square Meter (M2)'), ('M3', 'Cubic Meter (M3)'), ('LS', 'Lump Sum (LS)'),('Nos', 'Numbers (Nos)'), ('EA', 'Each (EA)'),('LM', 'Linear Meter (LM)'),('P.Sum', 'P.Sum (P.Sum)'), ('Item', 'Item (Item)'),('Unit', 'Unit (Unit)'),('Pcs', 'Pieces (Pcs)')], default='LS', max_length=10),
        ),
    ]
