# Generated by Django 6.0.4 on 2026-04-23 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_boqitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqitem',
            name='unit',
            field=models.CharField(choices=[("M", "M"), ("M2", "M2"), ("M3", "M3"), ("LS", "LS"),
        ("Nos", "Nos"), ("EA", "EA"), ("LM", "LM"),
        ("P.Sum", "P.Sum"), ("Item", "Item"), ("Unit", "Unit"),('Pcs', 'Pcs')], default='LS', max_length=10),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_type', models.CharField(choices=[('P', 'Proforma'), ('T', 'Tax')], default='P', max_length=1)),
                ('inv_number', models.IntegerField()),
                ('revision', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.project')),
            ],
        ),
    ]
