# Generated by Django 6.0.4 on 2026-04-23 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_boqitem_unit_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='advance_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='project',
            name='is_boq_complete',
            field=models.BooleanField(default=False, help_text='Check this to lock the BOQ and allow Invoicing'),
        ),
        migrations.AddField(
            model_name='project',
            name='retention_a_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='project',
            name='retention_b_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.DeleteModel(
            name='Invoice',
        ),
    ]
