# Generated by Django 6.0.4 on 2026-04-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_project_advance_percent_project_is_boq_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_boq_complete',
            field=models.BooleanField(default=False, help_text='Check this to lock the BOQ'),
        ),
    ]
