# Generated by Django 6.0.4 on 2026-04-23 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_alter_project_is_boq_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name='boqitem',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=12),
        ),
        migrations.AlterField(
            model_name='boqitem',
            name='unit',
            field=models.CharField(choices=[("M", "M"), ("M2", "M2"), ("M3", "M3"), ("LS", "LS"),
        ("Nos", "Nos"), ("EA", "EA"), ("LM", "LM"),
        ("P.Sum", "P.Sum"), ("Item", "Item"), ("Unit", "Unit"),('Pcs', 'Pcs')], default='LS', max_length=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='po_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_type', models.CharField(choices=[('P', 'Proforma'), ('T', 'Tax')], default='P', max_length=1)),
                ('inv_number', models.IntegerField()),
                ('revision', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.project')),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_qty', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('boq_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sales.boqitem')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.invoice')),
            ],
        ),
    ]
