# Generated by Django 6.0.4 on 2026-04-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_boqitem_quantity_alter_boqitem_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='billing_method',
            field=models.CharField(choices=[('QTY', 'By Quantity'), ('PCT', 'By Percentage')], default='QTY', max_length=3),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='current_percentage',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='boqitem',
            name='rate',
            field=models.DecimalField(decimal_places=6, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='current_qty',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
    ]
