# Generated by Django 6.0.4 on 2026-04-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_invoiceitem_billing_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='inv_number',
            field=models.IntegerField(help_text='Auto-suggested based on project history'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('project', 'inv_number', 'revision')},
        ),
    ]
