# Generated by Django 6.0.4 on 2026-04-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_alter_invoice_inv_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='inv_number',
            field=models.IntegerField(),
        ),
    ]
