# Generated by Django 6.0.4 on 2026-04-23 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_boqitem_quantity_alter_invoice_inv_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
