# Generated by Django 6.0.4 on 2026-04-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0011_alter_boqitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_advance_payment',
            field=models.BooleanField(default=False, help_text='Check if this is ONLY the Advance Payment Invoice'),
        ),
    ]
