# Generated by Django 6.0.4 on 2026-04-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_invoice_is_advance_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='cum_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='cum_percentage',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='cum_qty',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='current_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='prev_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='prev_percentage',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='prev_qty',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_advance_payment',
            field=models.BooleanField(default=False),
        ),
    ]
