# Generated by Django 6.0.4 on 2026-04-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_invoiceitem_cum_amount_invoiceitem_cum_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='is_advance_payment',
            field=models.BooleanField(default=False, help_text='Check if this is the Advance Payment Invoice'),
        ),
    ]
