# Generated by Django 6.0.4 on 2026-04-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_alter_invoice_is_advance_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqitem',
            name='unit',
            field=models.CharField(default='LS', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_advance_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='billing_method',
            field=models.CharField(choices=[('QTY', 'By Qty'), ('PCT', 'By %')], default='QTY', max_length=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_boq_complete',
            field=models.BooleanField(default=False),
        ),
    ]
