# Generated by Django 6.0.4 on 2026-04-24 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0015_alter_boqitem_unit_alter_invoice_is_advance_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='cum_amount',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='cum_percentage',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='cum_qty',
        ),
        migrations.RemoveField(
            model_name='invoiceitem',
            name='current_amount',
        ),
    ]
