# Generated by Django 6.0.4 on 2026-04-24 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0016_remove_invoiceitem_cum_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='inv_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
