# Generated by Django 6.0.4 on 2026-04-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_alter_invoice_inv_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqitem',
            name='unit',
            field=models.CharField(choices=[('M', 'M'), ('M2', 'M2'), ('M3', 'M3'), ('LS', 'LS'), ('LM', 'LM'), ('Pcs', 'Pcs'), ('Nos', 'Nos'), ('Item', 'Item'), ('EA', 'EA'), ('P.Sum', 'P.Sum')], default='LS', max_length=10),
        ),
    ]
