# Generated by Django 6.0.4 on 2026-04-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_alter_boqitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='boqitem',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_boq_complete',
            field=models.BooleanField(default=False, help_text='Confirm if BOQ Total matches PO Amount'),
        ),
    ]
