# Generated by Django 6.0.4 on 2026-04-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0019_alter_boqitem_quantity_alter_boqitem_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='current_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='current_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='prev_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='prev_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='prev_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
