# Generated by Django 6.0.4 on 2026-04-24 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0020_alter_invoiceitem_current_percentage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boqitem',
            options={'ordering': ['item_number']},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['project', 'inv_number', 'revision']},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['project_id_code']},
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='advance_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='gross_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='net_amount_value',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='rate',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='retention_a_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='retention_b_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='boqitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='boqitem',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='sales.project'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='current_percentage',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='current_qty',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='prev_amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='prev_percentage',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='prev_qty',
            field=models.DecimalField(decimal_places=5, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='sales.client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_boq_complete',
            field=models.BooleanField(default=False, help_text='Check to verify if BOQ Total matches PO Amount'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id_code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['project', 'inv_number'], name='sales_invoi_project_1ddd48_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceitem',
            index=models.Index(fields=['boq_item'], name='sales_invoi_boq_ite_6f0e0f_idx'),
        ),
        migrations.AddConstraint(
            model_name='invoice',
            constraint=models.UniqueConstraint(fields=('project', 'inv_number', 'revision'), name='unique_invoice_revision'),
        ),
    ]
