# Generated by Django 6.0.4 on 2026-04-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0021_alter_boqitem_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='sales_invoi_project_1ddd48_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoiceitem',
            name='sales_invoi_boq_ite_6f0e0f_idx',
        ),
        migrations.AlterField(
            model_name='boqitem',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='boqitem',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='current_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='current_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='net_amount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='prev_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='prev_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='prev_qty',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='retention_a_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='retention_b_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_boq_complete',
            field=models.BooleanField(default=False, help_text='Check to verify if BOQ matches PO Amount'),
        ),
        migrations.AlterField(
            model_name='project',
            name='po_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id_code',
            field=models.CharField(max_length=50),
        ),
    ]
