# Generated by Django 6.0.4 on 2026-04-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0022_remove_invoice_sales_invoi_project_1ddd48_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='is_advance_payment',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='vat_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_advance_invoice',
            field=models.BooleanField(default=False, help_text='Check only if this invoice is the advance payment invoice'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vat_percent',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5),
        ),
        migrations.AddField(
            model_name='project',
            name='po_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='po_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
