# Generated by Django 6.0.4 on 2026-04-26 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0023_remove_invoice_is_advance_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='prev_percentage',
        ),
        migrations.AlterField(
            model_name='boqitem',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='boqitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='boqitem',
            name='unit',
            field=models.CharField(choices=[('M', 'M'), ('M2', 'M2'), ('M3', 'M3'), ('LS', 'LS'), ('Nos', 'Nos'), ('EA', 'EA')], default='LS', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='is_advance_invoice',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='billing_method',
            field=models.CharField(choices=[('QTY', 'Qty'), ('PCT', '%')], default='QTY', max_length=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='is_boq_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id_code',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
