# Generated by Django 6.0.4 on 2026-04-26 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0024_remove_invoiceitem_prev_percentage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boqitem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='invoice',
            name='unique_invoice_revision',
        ),
    ]
