# Generated by Django 6.0.4 on 2026-04-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0025_alter_boqitem_options_alter_client_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='prev_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
