# Generated by Django 6.0.4 on 2026-04-26 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0027_invoice_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='invoiceitem',
            unique_together={('invoice', 'boq_item')},
        ),
    ]
