# Generated by Django 6.0.4 on 2026-04-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0028_alter_invoiceitem_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='material_supplied_by_client',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount to be deducted from the total payable.', max_digits=15),
        ),
    ]
