# Generated by Django 6.0.4 on 2026-04-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0029_invoice_material_supplied_by_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='material_supplied_by_client',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount to be deducted from the final payable amount after VAT.', max_digits=15),
        ),
    ]
