# Generated by Django 6.0.4 on 2026-04-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0030_alter_invoice_material_supplied_by_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='billing_method',
            field=models.CharField(choices=[('QTY', 'Qty'), ('PCT', '%')], default='PCT', max_length=3),
        ),
    ]
