# Generated by Django 6.0.4 on 2026-04-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0031_alter_invoiceitem_billing_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqitem',
            name='unit',
            field=models.CharField(choices=[('M', 'M'), ('M2', 'M2'), ('M3', 'M3'), ('LS', 'LS'), ('Nos', 'Nos'), ('EA', 'EA'), ('LM', 'LM'), ('P.Sum', 'P.Sum'), ('Item', 'Item'), ('Unit', 'Unit')], default='LS', max_length=10),
        ),
    ]
