# Generated by Django 6.0.4 on 2026-04-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0032_alter_boqitem_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='is_boq_complete',
            field=models.BooleanField(default=False, editable=False, help_text='Automatically set to True when BOQ total matches PO Amount.'),
        ),
        migrations.AlterUniqueTogether(
            name='invoice',
            unique_together={('project', 'inv_number')},
        ),
    ]
