# Generated by Django 6.0.4 on 2026-04-28 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0033_alter_project_is_boq_complete_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='material_supplied_by_client',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='gross_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='net_amount_value',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='prev_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='prev_percentage',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=8),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='prev_qty',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='retention_a_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='retention_b_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15),
        ),
    ]
