# Generated by Django 6.0.4 on 2026-04-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0035_companyprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='letter_footer',
            field=models.ImageField(blank=True, help_text='Invoice footer image', null=True, upload_to='company_footers/'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='letter_header',
            field=models.ImageField(blank=True, help_text='Invoice header image', null=True, upload_to='company_headers/'),
        ),
    ]
