# Generated by Django 6.0.4 on 2026-04-28 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0036_alter_companyprofile_letter_footer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='bank_info',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
