# Generated by Django 6.0.4 on 2026-04-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0037_companyprofile_bank_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='bank',
            field=models.TextField(blank=True, null=True),
        ),
    ]
