# Generated by Django 6.0.4 on 2026-04-29 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0038_companyprofile_bank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='bank_info',
        ),
    ]
