# Generated by Django 6.0.4 on 2026-05-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0039_remove_companyprofile_bank_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boqitem',
            name='unit',
            field=models.CharField(choices=[('M', 'M'), ('M2', 'M2'), ('M3', 'M3'), ('LS', 'LS'), ('Nos', 'Nos'), ('EA', 'EA'), ('LM', 'LM'), ('P.Sum', 'P.Sum'), ('Item', 'Item'), ('Unit', 'Unit'), ('Pcs', 'Pcs')], default='LS', max_length=10),
        ),
    ]
