# Generated by Django 6.0.4 on 2026-05-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0040_alter_boqitem_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='retention_recovery',
            field=models.CharField(blank=True, choices=[('', 'None'), ('A', 'Retention A'), ('B', 'Retention B')], default='', help_text='Recover previously deducted retention on this invoice. A and B must be recovered in separate invoices.', max_length=1),
        ),
    ]
