# Generated by Django 6.0.4 on 2026-05-01 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0041_invoice_retention_recovery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boqitem',
            options={'verbose_name': 'BOQ Item', 'verbose_name_plural': 'BOQ Items'},
        ),
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name': 'Company Profile', 'verbose_name_plural': 'Company Profile'},
        ),
    ]
