# Generated by Django 6.0.4 on 2026-05-15 18:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0042_alter_boqitem_options_alter_companyprofile_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Expense Category',
                'verbose_name_plural': 'Expense Categories',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('employee_type', models.CharField(choices=[('Staff', 'Office Staff'), ('Site', 'Site Worker')], default='Staff', max_length=10)),
                ('payment_type', models.CharField(choices=[('Bank', 'Bank Transfer'), ('WPS', 'WPS Agency'), ('Cash', 'Cash Payment')], default='Bank', max_length=10)),
                ('is_head_office', models.BooleanField(default=False, help_text='Head Office staff are prorated across projects monthly')),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('housing_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('transport_allowance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_allowances', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('annual_benefits', models.DecimalField(decimal_places=2, default=0, help_text='Annual benefits', max_digits=15)),
                ('annual_eid_cost', models.DecimalField(decimal_places=2, default=0, help_text='Annual Emirates ID', max_digits=15)),
                ('annual_visa_cost', models.DecimalField(decimal_places=2, default=0, help_text='Annual Visa', max_digits=15)),
                ('annual_ticket_cost', models.DecimalField(decimal_places=2, default=0, help_text='Annual Tickets', max_digits=15)),
                ('date_joined', models.DateField(default=datetime.date.today)),
                ('is_active', models.BooleanField(default=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='sales.project')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PayrollRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='First day of the month')),
                ('days_absent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('salary_advance', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('other_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('basic_salary_snap', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('housing_allowance_snap', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('transport_allowance_snap', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('other_allowances_snap', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('total_salary_snap', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('overtime_amount_snap', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('absence_deduction_snap', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('net_salary_snap', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('is_allocated', models.BooleanField(default=False)),
                ('allocated_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_records', to='sales.employee')),
            ],
            options={
                'verbose_name': 'Payroll Record',
                'verbose_name_plural': 'Payroll Records',
                'ordering': ['-month', 'employee__name'],
                'unique_together': {('employee', 'month')},
            },
        ),
        migrations.CreateModel(
            name='PayrollAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('admin_cost_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('total_allocated', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('project_work_done_pct', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('boq_item_work_done_pct', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('boq_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_allocations', to='sales.boqitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_allocations', to='sales.project')),
                ('payroll_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='sales.payrollrecord')),
            ],
            options={
                'verbose_name': 'Payroll Allocation',
                'verbose_name_plural': 'Payroll Allocations',
            },
        ),
        migrations.CreateModel(
            name='PricingProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_date', models.DateField(default=datetime.date.today)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_projects', to='sales.client')),
                ('reference_projects', models.ManyToManyField(blank=True, related_name='pricing_references', to='sales.project')),
            ],
            options={
                'verbose_name': 'Pricing Project',
                'verbose_name_plural': 'Pricing Projects',
            },
        ),
        migrations.CreateModel(
            name='PricingBOQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('unit', models.CharField(max_length=10)),
                ('estimated_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('historical_rate', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('historical_cost', models.DecimalField(decimal_places=2, default=0, editable=False, help_text='Cost per unit from past payroll + expenses', max_digits=15)),
                ('proposed_rate', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('proposed_total', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=15)),
                ('reference_boq_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_references', to='sales.boqitem')),
                ('pricing_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boq_items', to='sales.pricingproject')),
            ],
            options={
                'verbose_name': 'Pricing BOQ Item',
                'verbose_name_plural': 'Pricing BOQ Items',
                'ordering': ['item_number'],
            },
        ),
        migrations.CreateModel(
            name='SubExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_expenses', to='sales.expensecategory')),
            ],
            options={
                'verbose_name': 'Sub-Expense',
                'verbose_name_plural': 'Sub-Expenses',
                'unique_together': {('parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('is_allocated', models.BooleanField(default=False, help_text='True when cost is absorbed into BOQ items')),
                ('boq_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='sales.boqitem')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='sales.project')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='sales.expensecategory')),
                ('sub_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='sales.subexpense')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
                'ordering': ['-date'],
            },
        ),
    ]
