# Generated by Django 6.0.4 on 2026-05-15 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0043_expensecategory_employee_payrollrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='sales.employee', verbose_name='Employee')),
                ('to_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transferred_workers', to='sales.project', verbose_name='Temporary Project')),
            ],
            options={
                'verbose_name': 'Employee Transfer',
                'verbose_name_plural': 'Employee Transfers',
                'ordering': ['-from_date'],
            },
        ),
        migrations.CreateModel(
            name='PayrollCostCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(verbose_name='From Date')),
                ('to_date', models.DateField(verbose_name='To Date')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('payroll_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='sales.payrollrecord', verbose_name='Payroll Record')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payroll_cost_centers', to='sales.project', verbose_name='Project (Cost Center)')),
            ],
            options={
                'verbose_name': 'Payroll Cost Center',
                'verbose_name_plural': 'Payroll Cost Centers',
                'ordering': ['-from_date'],
            },
        ),
    ]
