# Generated by Django 6.0.4 on 2026-05-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0044_employeetransfer_payrollcostcenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetransfer',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Overtime Hours'),
        ),
        migrations.AddField(
            model_name='payrollcostcenter',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Overtime Hours'),
        ),
    ]
