# Generated by Django 6.0.4 on 2026-05-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0047_remove_employee_bank_name_remove_employee_iban_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetransfer',
            name='overtime_hours',
        ),
        migrations.RemoveField(
            model_name='payrollcostcenter',
            name='overtime_hours',
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Name'),
        ),
        migrations.AddField(
            model_name='employee',
            name='iban',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='IBAN'),
        ),
        migrations.AddField(
            model_name='employee',
            name='routing_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Routing Number'),
        ),
    ]
