# Generated by Django 6.0.4 on 2026-05-17 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0048_remove_employeetransfer_overtime_hours_and_more'),
    ]

    operations = [
    ]
