# Generated by Django 6.0.4 on 2026-05-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0049_auto_20260517_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollcostcenter',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Overtime Hours'),
        ),
    ]
