# Generated by Django 6.0.4 on 2026-05-17 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0050_payrollcostcenter_overtime_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeetransfer',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Bonus'),
        ),
        migrations.AddField(
            model_name='employeetransfer',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Overtime Hours'),
        ),
        migrations.AddField(
            model_name='payrollcostcenter',
            name='bonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Bonus'),
        ),
    ]
